export const questions = {
    "Microphone/Audio Issues": [
        "mein mikrofon funktioniert nicht in teams",
        "mein mikrofon funktioniert in microsfort teams",
        "teams hintergrund bilder",
        "mic not working",
        "i have teams issues",
        "ich habe ein problem mit Teams- mein Mikrofon funktionert nicht",
        "my camera is not working on teams",
        "Renaming of a URL of a MS Teams Sharepoint site",
        "microsoft word document template",
        "Wie authentifiziere ich mich am DruckgerÃ¤t?",
        "wie wende ich mich an die compliance abteilung?",
        "Mein Teams funktioniert nicht",
        "How can I manage E.ON emails on my mobile device using Microsoft applications like Outlook?",
        "How can I add external users to MS Teams meetings if they don't have an E.ON account?",
        "What are the recommended platforms for storing data within an organization, and where can I find the instructions for using OneDrive and MS Teams?",
        "Where can I access the instructions and user guides for Microsoft Office O365?",
        "How to order co-pilot for Microsoft 365",
        "How can I conduct live polls, Q&A sessions and quizzes in real time, creating a dynamic and participatory experience for audiences?",
        "Wer ist der Sicherheitsbeauftragte, der für mich verantwortlich ist?",
        "1. Nimm mich zum FuV-Tool\n2. Was ist das FuV-Tool?",
        "1. Nachrichten über die Kunstsammlung Nachrichten-Seite\n2. Wo finde ich Neuigkeiten über die E.ON Kunstsammlungen\n\n1. E.ON Kunstsammlung Online\n2. E.ON Kunst & Kultur und Designprojekte Seite\n3. Bring mich zur E.ON Kunstseite",
        "Wie man herausfindet, welcher Laptop perfekt für mich im modernen Arbeitsplatz ist",
        "An wen kann ich mich wenden, wenn ich Fragen zur digitalen Post habe?",
        "Wie man sich ohne E.ON-Konto mit entfernten Benutzern in MS Teams verbindet?",
        "So bestellen Sie den Co-Piloten für Microsoft 365",
        "What is Microsoft Copilot for Microsoft 365",
        "Can I use Teams or Planner from my private PC at home?",
        "I can’t generate a Teams meeting link in Outlook on the web.",
        "Teams camera not detected, what should I do?",
        "Teams screen sharing not working properly. Any fixes?",
        "Learn Microsoft Project",
        "Can Microsoft Project be integrated",
        "Quick tips about Microsoft Project"
    ],
    "Password Management": [
        "How to reset my Password?",
        "wie Ã¤ndere ich mein windows passwrt",
        "how can i reset my wondows password",
        "How do I reset my password?",
        "What is the WiFi network name and password for E.ON employees and guests in Germany for 2022?",
        "Can you provide the link to reset my SAP password?",
        "What is SAP Password Reset app?",
        "How to reset my password for SAP systems?",
        "How to reset my SAP system password?",
        "1. Wie verlängere ich die Zugriffsrechte meiner ID-Karte?\n2. Wie kann ich die Zugriffsberechtigungen auf meiner ID-Karte ändern?\n3. Wie kann ich die Zugriffsberechtigungen auf meiner ID-Karte erweitern?",
        "Wie man das SAP-Passwort zurücksetzt?",
        "Wie man das Windows-Passwort entsperrt? Konto entsperren?",
        "Was ist die Zurücksetzen des SAP-Passworts App?",
        "Wie setze ich mein Passwort für SAP-Systeme zurück?",
        "Wie setze ich das Passwort für mein SAP-System zurück?",
        "Wie setze ich mein Passwort zurück?",
        "Why am I being asked to update my device password?",
        "How do I update my device password?",
        "I cannot reset my PKI PIN. I'm getting a token verification error",
    ],
    "General Knowledge/Definitions": [
        "was ist scrum",
        "Was ist der Tranformation Navigator? Gib mir einen Link zur Home Seite.",
        "what is the official address of E.ON Digital technology",
        "what is N-3 managerial position",
        "What is the purpose of Zscalerâ€™s user authentication policy?",
        "was ist EIS",
        "What is the range for MPS-compatible badges?",
        "What is the appropriate URL to report an incident on the PRISMA platform?",
        "What is MobileIron and how does it enhance mobile device security and access to work applications?",
        "What is the procedure to return a computer or hardware through the service portal?",
        "What is the E.ON Campus and how can employees access its upskilling content?",
        "What is food menu in Würzburg?",
        "What is the food menu at Brüsseler Platz in Essen?",
        "What is food menu in Hannover?",
        "- What is beeline app?",
        "What is the app to efficiently manage your contingent workforce and streamline your staffing processes?",
        "- What is Ariba - Classic and Classic+ app?",
        "What is APP for procurement processes by having all the relevant information and tools in one place",
        "- What is Concur Travel Booking and Expenses app?",
        "what is the app to manage my travel expenses",
        "What is HR Portal app?",
        "What is the app to help my HR-related information and tasks in one place.",
        "What is Incidents app?",
        "What is Meeting Room Booking app?",
        "What is the app to manage workplace and meeting room bookings.",
        "What is My Assets app?",
        "What is the assets management application in myhelp (me@e.on)",
        "What is Order app?",
        "What is the application for ordering of IT applications within E.ON.",
        "What is Create Purchase Requisition app?",
        "What is Create Purchase Requisition Advanced app?",
        "What is Prisma app?",
        "What is the application to monitor and analyze my energy consumption and optimize.",
        "What is My Inbox app?",
        "What is the application to approve the invoices?",
        "What is Time-Tracking app?",
        "What is app easily track and manage your work hours, time and activities?",
        "What is CATS app?",
        "What is the app to track and mange our work hours, time and activites?",
        "What is Gertrud app?",
        "What is the app designed to assist users in preparing for board meetings.",
        "What is the app designed to assist for board meetings?",
        "- What is Notifcation Portal app?",
        "What is the centralized application designed to manage and streamline notifications within E.ON.?",
        "What is the centralized application to manage and streamline notifications?",
        "- What is Zuko app?",
        "What is the app which assists users in planning and organizing office relocations.",
        "What is the app assists for planning and organizing office relocations in E.ON",
        "What is EON Brand Space app?",
        "What is the app contain the guidelines for marketing and communications activities in E.ON",
        "What is PKI Portal app?",
        "What is digital certificate app?",
        "What is Mail DL app?",
        "What is the tool designed for managing distribution lists (DLs) used in email communications within the organization.",
        "What is the tool tool designed for managing distribution lists (DLs) used in email communication?",
        "What is Journeys/Events app?",
        "What is the app designed to facilitate the planning, management, and participation in various events and journeys within the organization.",
        "What is the app designed to facilitate the planning, management, and participation in various events and journeys.",
        "What is MyGenius app?",
        "What is digital learning platform for E.ON employees.",
        "What is the digital learning platform for E.ON employees.",
        "What is the digital learning platform",
        "What is idEE.ON app?",
        "What is the app to submit and evaluate ideas and suggestions?",
        "What is the app designed to facilitate a continuous improvement process in all areas of the company.",
        "What is Corporate SAC app?",
        "What is powerful visualization tool with advanced planning capabilities.",
        "What is the visualization tool with advanced planning capabilities.",
        "What is Redwood Finance Automation app?",
        "What is the app to consolidated financial statements and automate individual activities.",
        "What is the app to consolidated financial statements?",
        "What is EAM (200) app?",
        "What is self-developments based on Business technology plattform (BTP) from SAP",
        "What is SoD SAP Portal app?",
        "What is MAQSIMA TMS app?",
        "What is beqom app?",
        "- What is Talentry app?",
        "What is app to share our current job openings with talented people in your network",
        "What is Smart Guide app?",
        "What is Alteryx app?",
        "What is ROL app?",
        "What is Slido app?",
        "What is Corporate Portal app?",
        "What is VidE.ON app?",
        "What is Banking: Bank Acc Mgmt (EBAM) app?",
        "What is E.ON Guarantee Solution app?",
        "What is EPSnext app?",
        "What is FIS Quantum app?",
        "What is RMS - Risk Management app?",
        "What is DSE Software app?",
        "What is Gradar app?",
        "What is KYC app?",
        "What is SAM app?",
        "What is e-NORM app?",
        "What is Tagetik CPM app?",
        "What is Tagetik CPM and ERM app?",
        "What is Tagetik SAC app?",
        "What is getAbstract app?",
        "What is Digital Rulebook app?",
        "What is the Product Vision of MyHelp?",
        "What is MyHelp?",
        "What is MyHelp assistance and how does it work?",
        "Was ist ein Pocket Office?",
        "Was ist der moderne Arbeitsplatz?",
        "Was ist Ideenmanagement (idEE.ON)? Gibt es ein Ideenmanagement-Tool bei E.ON?",
        "Was ist Compliance?\nWelche Themen deckt Compliance ab?",
        "Was ist BIT Corporate / Unternehmensservice-Management",
        "Was ist myIT? Wo finde ich Details zu meinem IT- und E.ON ServiceHub oder Fileshare?",
        "Was ist E.ON Campus?\nWie kann man dem E.ON Campus beitreten?\nWeiterbildungsplattform für die Cloud bei E.ON?",
        "Was ist QuickAccess / TTSPS? Gibt es eine Suchmaschine, die Mitarbeiter nutzen können, um Lerninhalte zu finden?",
        "Was ist PowerAutomate? Wie kann ich Prozesse in O365 automatisieren?",
        "Was ist Vertec? In welchem Tool kann ich Engagements berechnen und berichten?",
        "Was ist CoPlanner? Ist es ein Tool zur Planung bei E.On? Controlling-Software für Planung & Reporting.",
        "Was ist die Beeline-App?",
        "Was ist die App, mit der Sie Ihr externes Personal effizient verwalten und Ihre Personalbeschaffungsprozesse optimieren können?",
        "Was ist die Ariba Classic- und Classic+-App?",
        "Was ist APP für Beschaffungsprozesse, wenn alle relevanten Informationen und Werkzeuge an einem Ort zur Verfügung stehen?",
        "Was ist die Concur-Reisebuchung und -Kosten App?",
        "Was ist die App, um Ihre Geschäftsreisen und Spesenabrechnungen einfach zu verwalten und einzureichen.",
        "-Was ist die App, um unsere Geschäftsreisen und Spesenabrechnungen einfach zu verwalten und einzureichen.",
        "Was ist die HR Portal App?",
        "Was ist die App, die mir hilft, meine HR-bezogenen Informationen und Aufgaben an einem Ort zu sammeln.",
        "Was ist die Incidents App?",
        "Was ist die Raumbuchungen App?",
        "Was ist die App zur Verwaltung von Arbeitsplatz- und Besprechungsraumbuchungen.",
        "Was ist die Meine IT Ausstattung App?",
        "Was ist die Vermögensverwaltungsanwendung in myhelp (me@e.on)?",
        "Was ist die Bestellungen App?",
        "Was ist die Anwendung für die Bestellung von IT-Anwendungen bei E.ON?",
        "Was ist die Bestellanforderung erstellen App?",
        "Was ist die Erweiterte Bestellanforderung erstellen App?",
        "Was ist die Prisma App?",
        "Was ist die Anwendung zur Überwachung und Analyse meines Energieverbrauchs und zur Optimierung.",
        "Was ist die My Inbox App?",
        "Was ist die Anwendung zur Genehmigung von Rechnungen?",
        "Was ist die Zeiterfassung App?",
        "Was ist eine App, mit der Sie Ihre Arbeitsstunden, Zeit und Aktivitäten leicht verfolgen und verwalten können?",
        "Was ist die CATS-App?",
        "Was ist die App zum Erfassen und Verwalten unserer Arbeitszeiten, Zeit und Aktivitäten?",
        "Was ist die Gertrud App?",
        "Was ist die Meldungsportal App?",
        "Was ist die zentrale Anwendung zur Verwaltung und Rationalisierung von Benachrichtigungen innerhalb von E.ON?",
        "Was ist die zentralisierte Anwendung zur Verwaltung und Rationalisierung von Benachrichtigungen?",
        "Was ist die Zuko App?",
        "Was ist die App, die den Nutzer bei der Planung und Organisation von Büroumzügen unterstützt.",
        "Was ist die App, die bei der Planung und Organisation von Büroumzügen in E.ON hilft?",
        "Was ist die EON Brand Space App?",
        "Was ist die App, die die Richtlinien für Marketing- und Kommunikationsaktivitäten bei E.ON enthält?",
        "Was ist die PKI Portal App?",
        "Was ist die Mailverteiler App?",
        "Was ist die Fahrten und Veranstalltungen App?",
        "Was ist die App, die die Planung, Verwaltung und Teilnahme an verschiedenen Veranstaltungen und Reisen innerhalb der Organisation erleichtern soll.",
        "Was ist die App, die die Planung, Verwaltung und Teilnahme an verschiedenen Veranstaltungen und Reisen erleichtern soll.",
        "Was ist die MyGenius App?",
        "Was ist die digitale Lernplattform",
        "Was ist die idEE.ON App?",
        "Was ist die App, die einen kontinuierlichen Verbesserungsprozess in allen Bereichen des Unternehmens ermöglichen soll?",
        "Was ist die Corporate SAC App?",
        "Was ist die Redwood Finance Automation App?",
        "Was ist die App zum konsolidierten Jahresabschluss und zur Automatisierung einzelner Aktivitäten.",
        "Was ist die App zum konsolidierten Jahresabschluss?",
        "Was ist die EAM (200) App?",
        "Was ist die EAM (100) App?",
        "Was ist die SoD SAP Portal App?",
        "Was ist die MAQSIMA TMS App?",
        "Was ist die beqom App?",
        "Was ist die Talentry App?",
        "Was ist die Smart Guide App?",
        "Was ist die Alteryx App?",
        "Was ist die ROL App?",
        "Was ist die Slido App?",
        "Was ist die Corporate Portal App?",
        "Was ist die VidE.ON App?",
        "Was ist die Banking: Bank Acc Mgmt (EBAM) App?",
        "Was ist die E.ON Guarantee Solution App?",
        "Was ist die EPSnext App?",
        "Was ist die FIS Quantum App?",
        "Was ist die RMS - Risk Management App?",
        "Was ist die Insights Library App?",
        "Was ist die Achieving My Potential App?",
        "Was ist die DSE Software App?",
        "Was ist die Gradar App?",
        "Was ist die KYC App?",
        "Was ist die SAM App?",
        "Was ist die e-NORM App?",
        "Was ist die Tagetik CPM App?",
        "Was ist die Tagetik CPM and ERM App?",
        "Was ist die Tagetik SAC App?",
        "Was ist die getAbstract App?",
        "Was ist die Digital Rulebook App?",
        "Was ist die Produktvision von MyHelp?",
        "Was ist MyHelp?",
        "Was ist MyHelp Assistance und wie funktioniert es?",
        "Was ist neu in MyHelp?",
        "What is brown box icon on a OneDrive file",
        "What is the appropriate channels for reporting a theft?",
        "What is food menu in München?"
    ],
    "Other": [
        "Ich möchte ein Snow Ticket eröffnen",
        "Wie kann ich einen physischen USB-Token erhalten, um virtuelle Smart Cards auf Cloud-PCs zu verwenden?",
        "Wo ist die PPT-Vorlage für EON?",
        "Gibt es zu API keine Info in Connect?",
        "EDT HR Rollen",
        "i need to book a seat in munich arnulfstrasse",
        "EDT Invoice Address",
        "wie kann ich ein neues handy bestellen?",
        "Hallo, wie Ã¤ndere ich das Titelbild eines Items in SAP Success Factors?",
        "how to install ms365 in my machine",
        "I heard there is a perk to get German language course. Where can I find more information about it",
        "ich kann auf myHR nicht zugreifen",
        "How to use Axway",
        "can you give me the link to the relevant doc",
        "Termin im walk-in center buchen",
        "can you give me a list of EDT office locations?",
        "is there an EDT office in chemnitz?",
        "how can I get github copilot license in e.on",
        "can i send packages between locations",
        "Wer ist meine Asprechperson?",
        "Wo kann ich in Essen RTk parken",
        "Personalakte ausleihen",
        "how can i track my time",
        "Wie kann ich einen Taxibeleg als Reisekosten abrechnen?",
        "what's the dog policy of EGS in hamburg in the normannenweg office",
        "Wie bekomme ich empower?",
        "where do I find the concur user guide?",
        "Nautilus",
        "wofÃ¼r steht die abkÃ¼rzung IBU",
        "Do you have the link to the channel?",
        "wer ist mein Manager",
        "Who is teh president of US?",
        "Can I also book a room in k1 building?",
        "I did this, but it did not help?",
        "CS Universe-ity",
        "ich mÃ¶chte einen Power BI workspace bestellen",
        "und supply chain?",
        "I did that and it did not help. What else can I do?",
        "I tried this, but it did not help. What else can I do?",
        "Warum wird meine SKID nicht in Entra angezeigt?",
        "That has not helped",
        "Wo finde ich das CTI Dashboard",
        "i want to order a linux server in the azure cloud",
        "wie erreiche ich den service desk",
        "Jira Lizenz fÃ¼r User beantragen",
        "Welches Hotel befindet sich in Essen in der NÃ¤he vom KohleCraftWerk Restaurant",
        "wie beantrage ich einen Besucherausweis am BBrÃ¼sseler Platz?",
        "wie kann ich einen externen Kandidaten fÃ¼r eine Stelle bei E-On empfehlen?",
        "wo finde ich die offizielle dokumentation?",
        "Welche GebÃ¤ude gehÃ¶ren der E.ON Auf dem Ruhr Tech Kampus?",
        "Ich suche das Organigramm der Corporate Digital Technology",
        "user lizenz bentragen",
        "ich mÃ¶chte mitarbeiteraktien zeichnen",
        "wie kann ich pocket office einrichten",
        "Gib mir bitte den Link zum GRC System.",
        "Wie kann ich ein Vnet bestellen?",
        "wie kann ich im AAD die Stammdaten Ã¤ndern?",
        "Wie kann ich eine BahnCard 100 beantragen",
        "Computer Refresh",
        "wer ist der CEO von E.ON?",
        "wie bestelle ich ein Postfach",
        "Ich mÃ¶chte aus dem Azure tenant Laufwerk daten encryptet kopieren lassen auf eien externe Harddisk",
        "Mein Video bricht immer ab",
        "I am looking for an AI training",
        "Where can I find the guidelines to set up and activate a new mobile phone?",
        "Where can you find showers in Essen, and what facilities are provided?",
        "Where can I find information about laundry services available at different office locations?",
        "Where can I find the FuV Tool on the corporate portal?",
        "Where can I find information on how to add a printer to my system?",
        "What services are offered at the ID card center?",
        "How can I pre-order my food at E.ON canteens?",
        "Where can I request a new ID card for an employee at E.ON?",
        "What should I do if I've lost my ID card, and where can I find assistance?",
        "Where can I apply for an extension of access rights on my ID card?",
        "Where can E.ON employees find special offers and benefits on their dedicated portals?",
        "Where can I find my monthly payslip on the HR portal?",
        "Where can I book my absences and view my vacation days online?",
        "How can I contact the HR service line or HR direct, including phone numbers and email?",
        "Where can I find information on leasing a company car through my organization?",
        "Where can I find the application form for the A1 certificate required for traveling?",
        "Where can I access the SAP Space Management tool for relocation?",
        "Where can I find more information about EON Team Electricity and Gas?",
        "Where can I find detailed information about laptops suitable for a modern workplace?",
        "Where can I find information about parent-child rooms at various locations?",
        "Where can I find detailed information about the Idea Management system (idEE.ON) used by E.ON?",
        "Where can I access comprehensive guides and manuals on various IT topics provided by IT Service Communication?",
        "What are the emergency contact options and resources available for travelers needing urgent assistance?",
        "Where can I find current security alerts and situations for countries I'm planning to travel to?",
        "Where can I find detailed information on physical security and business resilience for my organization?",
        "Where can I find the contact persons for Business Resilience at E.ON?",
        "Where can I find details about the E.ON employee stock and investment plan?",
        "Can you provide the links to access the various employee benefits and offers for E.ON employees?",
        "What steps should I take to contact the ID Card Center for unblocking my ID card?",
        "Who should I contact if I'm unable to pay with my badge in the canteen?",
        "How can I transfer the remaining credit from my old card to my new one through the ID Card Center?",
        "Where can I access the ID card request forms for E.ON Service GmbH online?",
        "How long is the access period for external company or partner badges before they need renewal?",
        "Where can I find the form to apply for a cost center badge for my department?",
        "Where can I find the appropriate channels for reporting a theft?",
        "Where can I report an accident, such as one in a garage, through online platforms or designated centers?",
        "Where can I report a drone sighting near a building, and is there an online link to the Security Response Center (SRC)?",
        "Where can I find comprehensive resources on cyber security provided by PG Group Information Security?",
        "Where can I find detailed resources on the Cyber Emergency Response Team (CERT) and Cyber Threat Intelligence (CTI)?",
        "Where can I find detailed information and resources about penetration testing within the organization?",
        "Where can I find comprehensive resources for understanding vulnerability management?",
        "Where can I subscribe to receive Cyber Security notifications?",
        "Where can I access the Code of Conduct and employee guidelines?",
        "Where can I find guidelines for submitting an anonymous whistleblowing report at E.ON?",
        "Where can I access E.ON's Digital Rulebook online?",
        "Where can employees find information about discounts on motor vehicle liability and automobile collision insurance?",
        "Where can I find detailed information about money laundering?",
        "Where can I find detailed information about donations and sponsoring?",
        "Where can I find detailed guidelines on invitations and gifts?",
        "Where can employees find special offers for electricity and gas?",
        "Where can I find a list of my current IT service tickets?",
        "How can I get support or additional information about the digital postal mail service?",
        "Where can I find more information about the telephone switchboard services and their operating hours?",
        "Where can I find information about technical building services in various cities like Essen, Dortmund, Munich, and Hannover?",
        "Where can I find information about the Security Response Center (SRC) for Essen BP, and are there resources for other locations?",
        "Where can I find facility management details for Essen BP and other locations?",
        "How can I register an external employee using the data recording form?",
        "Where can I find more information about Corporate Service Management?",
        "How can I contact the Global Service Desk to unlock my Windows account?",
        "Where can I access the Corporate Portal?",
        "Where can I access the Ariba Spend Management and get permissions for the Ariba Mall?",
        "Where can I find resources or links for identity and access management in the S/4 United system?",
        "Where can I find detailed information about IT@E.ON and related services such as E.ON ServiceHub and Fileshare?",
        "Where can I find the links to the German HR Portal and other HR Portals for E.ON?",
        "Where can I place an order for Citrix Virtual Desktops?",
        "How can I set up access to emails, Office 365 applications, and the intranet from a private device?",
        "Where can I find information and request access to project management and virtual collaboration tools like Jira, Miro, and Slack?",
        "Where can employees find QuickAccess and TTSPs for learning content?",
        "How can I locate my PC's name using the computer properties?",
        "What features does the Vertec tool offer for project and portfolio management?",
        "Where can I find detailed information about CoPlanner and how it is used for planning and reporting in E.On?",
        "Where can I initiate the initial announcement to the works council?",
        "How to order food at ruhr tech campus?",
        "How to get to ruhr tech Campus?",
        "What are emergency management contacts?",
        "Where to get Employee ID cards ruhr tech kampus?",
        "Where is IT Walk-In Center at ruhr tech Campus?",
        "How to return a smartphone, Tablet or an Iphone?",
        "Can you show me the Avacon org chart?",
        "Can you show me the Bayernwerk org chart?",
        "Can you show me the E.DIS org chart?",
        "Can you show me the enviaM org chart?",
        "Can you show me the Hansewerk org chart?",
        "Can you show me the Lechwerke org chart?",
        "Can you show me the E.ON Digital Technology org chart?\n\nEDT org chart",
        "Can you show me the German Sales org chart?",
        "Can you show me the Poland org chart?",
        "Can you show me the PreussenElektra org chart?",
        "Can you show me the Romania org chart?",
        "Can you show me the Suwag org chart?",
        "Can you show me the Swedish org chart?",
        "Can you show me the E.ON Country Hub Germany org chart?",
        "Can you show me the E.ON Gastronomy GmbH org chart?",
        "Can you show me the E.ON impulse GmbH org chart?",
        "Can you show me the E.ON Solutions GmbH org chart?",
        "Can you show me the Westenergie org chart?",
        "Can you show me the E.ON Energy Markets org chart?",
        "How to get to the Office in Würzburg?",
        "What are emergency management contacts in Würzburg?",
        "Where to get Employee ID cards in Würzburg?",
        "Where is IT Walk-In Center at Würzburg?",
        "How to get to the Brüsseler Platz in Essen?",
        "What are emergency management contacts in Essen?",
        "Where to get Employee ID cards at Brüsseler Platz?",
        "Where is IT Walk-In Center at Essen?",
        "How to get to the Office in München?",
        "What are emergency management contacts in München?",
        "Where to get Employee ID cards in München?",
        "Where is IT Walk-In Center in München?",
        "How to get to the Office in Hannover?",
        "What are emergency management contacts in Hannover?",
        "Where to get Employee ID cards in Hanover?",
        "Where is IT Walk-In Center in Hannover?",
        "From where I can manage and submit my travel and expense reports",
        "where I can manage and submit my travel and expense",
        "Where I can conveniently access and manage for HR-related information and tasks in one place.",
        "From where I can access and manage for HR-related information and tasks.",
        "Which app is designed for the management and tracking of ServiceNow incidents that disrupt normal service operations?",
        "How to book/manage for workplace meeting room.",
        "Where I can get my assets related details?",
        "Where I can get my assets details?",
        "How I can get my assests details?",
        "Where I can see/check my IT order status in E.ON?",
        "Where I can get goods and services relevant details?",
        "Application for goods service relevant functions?",
        "How to get goods and service relevant details?",
        "How to I get goods and service relevant status?",
        "Where I can see goods and service relevant update?",
        "How to monitor and analyze my(our) energy consumption and optimize.",
        "Where do we monitor and analyze our energy consumption and optimize in one place.",
        "How I can easily (efficiently) approve the invoices\n(by having all the relevant information)",
        "How to approve the invoices?",
        "Which is centrally manage app to manage and streamline notifications within E.ON?",
        "From Where we/I can see the necessary guidelines for marketing and communications activities in E.ON",
        "Digital certificate app?",
        "Whats is EAM (100) app?",
        "Which app is designed to streamline and digitize the management of Segregation of Duties?",
        "Which tool is essential for maintaining a robust internal control system and safeguarding your business operations.",
        "Which app helps you to quickly and easily keep track of all relevant risk assessments",
        "Which app is used for administration and communication of E.ON long-term incentive plans?",
        "Who uses beqom app?",
        "Which app is used to provide policies in the areas IFRS, Controlling, HGB and ESG.",
        "How can users manage and share analytic applications and workflows",
        "Which app provides real-time updates on environmental, health, and safety (EHS) regulations?",
        "How to maintain a safe and compliant workplace, reducing risks, and improving operational efficiency?",
        "-Which is the central internal application platform?",
        "-Which app can be used to book services for a video/TV production at Brüsseler Platz?",
        "How can I streamline and manage the processes associated with bank account management electronically?",
        "Which app takes over surety and guarantees for BU's of the group to external lenders.",
        "How can I streamline document management processes within the organization?",
        "Which app provides a comprehensive solution for handling document management?",
        "Which app provides real-time visibility into cash and liquidity, enabling better decision-making on capital and risk management?",
        "Which app streamlines workflows and improve financial performance?",
        "Which app can be used for credit application processing and credit risk management?",
        "Whats is Insights Library app?",
        "Which is E.ON’s central knowledge repository for customer & market insights?",
        "Whats is Achieving My Potential app?",
        "Which is the app used to record their performance, objectives and reviews for UK Employees and Managers?",
        "Which app can be used to display screen training and assessments for Health and Safety.",
        "Which app is used to start the grading process of leading employees.",
        "With which tool you can screen counterparties?",
        "How can I execute mandatory safety trainings?",
        "How can I manage, provide, and update data related to quality assurance or standard documents?",
        "Which is Corporate Performance Management application?",
        "Which app is used for budgeting & planning, consolidation, risk and Management reporting",
        "Which is Enterprise Risk Management application?",
        "Which is the dashboarding app for Group Financial, ESG Reporting, Unit Financial and FSOTC Dashboard?",
        "Which is the online library app with book summaries, articles and further learning formats which cover all business relevant skills?",
        "Which app can be referred for soft skills and functional skills?",
        "Which app provides the guidelines of their company?",
        "Who is Leonhard Birnbaum?",
        "Who is Leo?",
        "Who is the CEO of E.ON?",
        "Can you share me the link to EON GPT?",
        "What are Corp Apps use cases?",
        "What are Workplace Apps Search use cases?",
        "Who is Praveen kumar?",
        "Wie meldet man einen Vorfall auf PRISMA? Ein Vorfallbericht auf Prisma öffnen?",
        "Was sind die aktuellen Corona-Regeln an meinem Standort? Gibt es Einschränkungen an meinem Standort? Brauche ich einen Corona-Test an meinem Standort? Brauche ich eine Maske an meinem Standort? Gibt es Einschränkungen für die Anzahl der Mitarbeiter pro Büro? Werden die Mitarbeiter gebeten, einen Selbsttest vor dem Betreten eines Standorts durchzuführen? Stellt E.ON kostenlose Selbsttest-Kits für Mitarbeiter zur Verfügung?",
        "Wie bekommt man einen höhenverstellbaren Schreibtisch?",
        "Wie kann ich mein Mobiltelefon aktivieren?",
        "Wie gebe ich meinen alten Computer zurück?",
        "Gibt es Duschen in Essen?",
        "Wie funktioniert der Wäscheservice? Gibt es einen Wäscheservice an meinem Standort? Gibt es einen Service, um meine schmutzige Kleidung im Büro zu waschen?",
        "Wie füge ich einen Drucker zu meinem System hinzu? Wie drucke ich?",
        "Personalausweis Hilfe mit Personalausweis",
        "1. Kann ich mein Mittagessen vorbestellen?\n2. Kann ich mein Mittagessen in [ORT] bestellen?\n3. Ist eine Vorbestellung in den E.ON-Kantinen möglich?\n4. Wo kann ich mein Essen vorbestellen?",
        "1. Wie bekomme ich eine neue Mitarbeiterausweis-Karte?\n2. Wo kann ich ein neues Namensschild bestellen?\n3. Wie kann ich eine neue Identifikationskarte erhalten?\n4. Wie kann ich eine neue ID-Karte bestellen?\n5. Wie erhalte ich eine neue Identifikationskarte?",
        "1. Muss ich den Verlust meines Ausweises melden? Wenn ja, wo?\n2. Ist es notwendig, den Diebstahl meines Ausweises zu melden?\n3. Soll ich den Verlust meines Ausweises melden?\n4. Ist es notwendig, den Diebstahl/Verlust meines Mitarbeiterausweises zu melden?",
        "1. E.ON Aktienkurs\n2. Wie kann ich die E.ON Aktienkurse sehen?",
        "1. Mitarbeiterbeitragsseite\n2. Können E.ON-Mitarbeiter irgendwelche Beiträge/Angebote erhalten?\n3. Bietet E.On spezielle Angebote für Mitarbeiter an?\n4. E.ON-Mitarbeiterbenefits-Portale",
        "1. Meine Gruppen-ID\n2. Meine persönliche Nummer\n3. Meine KID\nKonzern-ID\nKonzern-Identifikationsnummer",
        "1. Wo finde ich meine IT-Asset-Nummern\n2. Meine Asset-Details\n3. Die Seriennummer meines Computers/Laptops",
        "1. Monatliche Gehaltsabrechnungen\n2. Meine Gehaltsabrechnung",
        "Überblick über den Urlaub\nUrlaubsdetails\nMeine Urlaubspläne\nWie buche ich meinen Urlaub?",
        "1. Holen Sie sich meinen HR-Ansprechpartner\n2. HR-Kontaktdaten\n3. Mein HR-Kontakt\n4. HR Direkt",
        "Wie kann ich ein Firmenauto leasen?",
        "Gibt es einen Rabatt auf Fahrscheine für den öffentlichen Nahverkehr für die Mitarbeiter des Unternehmens? Zugunterstützung \"Unternehmenskarten der VRR\" von EON in Essen?",
        "A1-Zertifikat für Reisen",
        "Fitnessraum, Öffnungszeiten, Anmeldung, Kontakt Trainer, Gibt es ein Fitnessstudio an meinem Standort?",
        "WIFI-Codes für E.ON-Mitarbeiter und Gäste",
        "Job-Fahrrad\nWo kann ich die Details zum Job-Fahrrad finden?",
        "Bitte öffne mir das Umzugsmanagement-Tool",
        "EON Team Elektrizität",
        "Gibt es ein Eltern-Kind-Zimmer bei mir?",
        "Wo kann ich Tutorials / Leitfäden / Handbücher / Anleitungen zu verschiedenen IT-Themen finden?",
        "1. Wo finde ich Informationen zur Reisewirtschaft? 2. Gibt es Informationen zur Reisewirtschaft? 3. Haben wir etwas zur Reisewirtschaft? 4. Hat E.ON etwas über Sicherheit beim Reisen? 5. Reisewirtschaft?",
        "1. Haben wir eine Notfallnummer während der Reise? 2. Haben wir einen Notfallkontakt während der Reise? 1. Wo kann ich anrufen, wenn ich im Ausland einen Notfall habe? 2. Wen kann ich im Falle eines Notfalls während der Reise anrufen?",
        "1. Muss ich Sicherheitsaspekte für ein Land berücksichtigen? 2. Kann ich Informationen über das Land erhalten, in das ich reise?",
        "1. Physische Sicherheit?\n2. Sicherheit?",
        "1. Wer ist für die physische Sicherheit verantwortlich?\n2. Wer ist für das Bedrohungsmanagement verantwortlich?\n3. Wer ist für das Management der Geschäftskontinuität verantwortlich?\n4. Wer ist für das Krisenmanagement verantwortlich?",
        "1. Einzelheiten zum Aktienprogramm\n2. E.On Investitionsplan",
        "1. Details aller Mitarbeiterleistungen aufgelistet\n2. Alle Leistungen, die E.ON-Mitarbeitern angeboten werden\n3. Nennen Sie mir alle meine Mitarbeiterleistungen",
        "Mein Personalausweis ist gesperrt, wie kann ich ihn entsperren lassen?",
        "Ich kann in der Kantine nicht mit meinem Badge bezahlen, was muss ich tun?",
        "Ich habe noch Guthaben auf meiner alten Karte, kann das auf meine neue Karte übertragen werden?",
        "Wo kann ich die Anträge für Ausweise / Zugangs Antragsformulare finden?",
        "Wie lange ist die Zugangsdauer für die ID-Karte?",
        "Wie bekomme ich einen Kostenstellenausweis für meine Abteilung?",
        "Wo melde ich einen Diebstahl?",
        "Wo melde ich einen Unfall, der in der Garage passiert ist?",
        "Wie melde ich eine Sichtung einer Drohne über dem Gebäude?",
        "Wo kann ich Informationen zur Cybersicherheit finden?",
        "Wo kann ich mehr Informationen über CERT / CTI finden?",
        "Wie fordere ich Unterstützung für einen Penetrationstest an? Wo kann ich weitere Informationen über Penetrationstests finden?",
        "Wo kann ich weitere Informationen über Schwachstellenscans finden?",
        "Wie kann ich Cyber-Sicherheitsbenachrichtigungen erhalten?",
        "1. Gibt es ein digitales Nachschlagewerk in der Gruppe?\n2. Digitales Regelwerk?\n3. Wo kann ich das digitale Regelwerk von E.ON finden?\n4. Gibt es einen Chatbot zum digitalen Regelwerk?",
        "Gibt es Rabatte für Mitarbeiter bei Versicherungen?",
        "Was muss ich über Spenden und Sponsoring wissen?",
        "Welche Regeln gelten für Einladungen und Geschenke?",
        "Gibt es Angebote für Mitarbeiter für Strom und Gas?",
        "Zeig mir meine aktuellen IT-Service-Tickets",
        "Servicezeiten Telefonzentrale\nZentralendienstleistungen\nTelefonzentrale\nCallcenter\nKontaktieren Sie das Personal der Telefonzentrale",
        "Technische Facility-Services\nTechnischer Gebäudedienst\nWer sorgt dafür, dass Gebäude und Systeme ordnungsgemäß funktionieren?",
        "Sicherheitszentrum\nSicherheitsreaktionszentrum\nSRC",
        "Einzelheiten zum Facility Management\nDetails zum Facility Management?",
        "Externe Mitarbeiter registrieren\nWie man externe Mitarbeiter bestellt\nDaten eingeben für externe Mitarbeiter",
        "Link zum Unternehmensportal?",
        "Link für Ariba / B2B / Bürobedarfskatalog. E.ON Einkaufsservice?",
        "Wo kann ich Informationen zu SAP-Berechtigungen finden?",
        "Link zum myHR-Portal\nMein HR-Portal",
        "Wie kann ich VDI Citrix Virtual Desktops bestellen?",
        "Wie fügt man E.ON Mails auf mobilen Geräten / Mobiltelefonen hinzu?",
        "Wie fügt man den Zugriff von einem privaten Gerät auf E-Mails, Office oder Intranet hinzu?",
        "Wo kann ich Informationen zu Jira / Confluence / Trello / Miro / Mattermost / Slack Zugangsbestellungen finden? Projektmanagement-Software. Digitale Werkzeuge für virtuelle Zusammenarbeit.",
        "Wie heißt mein PC? Wo kann ich meinen PC-Namen finden?",
        "Wo finde ich die Erstanzeige an den Betriebsrat?",
        "Speiseplan at ruhr tech Kampus",
        "Anreise at ruhr tech kampus",
        "Notfallmanagement ruhr tech campus",
        "Mitarbeiterausweise ruhr tech kampus",
        "Standort Ruhr Tech Campus",
        "ein Smartphone, Tablet oder ein Iphone zurückgeben",
        "Avacon\nAva\nAVA: Unternehmen\nAvacon Orga\nAva Orga\nAvacon Organigramm\nAVA Organigramm",
        "Bayernwerk\nBAG\nBayernwerk Orga\nBAG Orga\nBAG: Organisationshandbuch/ Regelwerke/ Formulare\nBayernwerk Organigramm\nBAG Organigramm",
        "E.DIS: Organisationshandbuch\nE.DIS Organigramm\nE.DIS Organigramme\nE.DIS Organisations Chart\nEDIS: Organisationshandbuch\nEDIS Organigramm\nEDIS Organigramme\nEDIS Organisationschart",
        "enviaM: Unternehmensgruppe\nOrganigramme enviaM-Gruppe\nenviaM Organigramm",
        "HAW: HanseWerk-Gruppe\nHansewerk Organigramm\nHAW Organigramm\nOrganigramme der HanseWerk-Gruppe",
        "LEW: Unternehmen\nLechwerke Organigramm\nLEW Organigramm\nLechwerke Org Chart\nLEW Org Chart\nLEW Organigramme und Funktionsbereiche\nLechwerke Organigramme und Funktionsbereiche",
        "E.ON Digital Technology Organigramm\nEDT Org Organigramm\nEDT Organisationsschart\nEDT GmbH Organizational Chart / EDT GmbH Legale Organisation\nEDT: About E.ON Digital Technology",
        "German Sales Organigramm\nGer Sales Organigramm",
        "Polen Organigramm\nPolnisches Organigramm",
        "PEL: Unser Unternehmen\nPreussen Elektra Organigramm\nPE Organigramm",
        "Rumänien Organigramm",
        "Süwag Organigramm",
        "Schweden Organigramm\nSchwedisches Organigramm\nSchweden Org Chart\nSchwedisches Org Chart\nOrganisationsschema",
        "E.ON Country Hub Germany Organigramm\nE.ON Country Hub Germany Org Chart\nCountry Hub Germany Organigramm\nCountry Hub Germany Org Chart\nDE: E.ON Country Hub Germany GmbH (ECG)",
        "E.ON Gastronomy GmbH Organigramm\nE.ON Gastronomy GmbH\nE.ON Gastro Organigramm Org Chart\nE.ON Gastro Org Chart\nGastronomy GmbH Organigramm\nGastronomy GmbH\nGastro Organigramm Org Chart\nGastro Org Chart\nDE: E.ON Gastronomie GmbH",
        "E.ON impulse GmbH Organigramm\nE.ON impulse Organigramm\nimpulse GmbH Organigramm\nimpulse Organigramm\nDE: E.ON impulse GmbH",
        "E.ON Solutions GmbH Organigramm\nE.ON Solutions Organigramm\nSolutions GmbH Organigramm\nSolutions Organigramm\nPeopletopics @ COO-C",
        "Westenergie Organigramm\nWestnetz Organigramm\nWestenergie: Organisationshandbuch der Westenergie Gruppe\nOrganigramme der Westenergie Gruppe",
        "Energy Markets Organigramm\nEnergy Markets",
        "Was gibt es in der Kantine in Würzburg?",
        "Wie komme ich zum Büro in Würzburg?",
        "Welche Notfallkontakte gibt es in Würzburg?",
        "Wo bekomme ich meinen Mitarbeiterausweis in Würzburg?",
        "Wo befindet sich das IT Walk-In Center in Würzburg?",
        "Was gibt es in der Kantine in am Brüsseler Platz in Essen ?",
        "Wie komme ich zum Brüsseler Platz in Essen?",
        "Welche Notfallkontakte gibt es am Brüsseler Platz in Essen?",
        "Wo bekomme ich meinen Mitarbeiterausweis am Brüsseler Platz?",
        "Wo befindet sich das IT Walk-In Center in Essen?",
        "Was gibt es in der Kantine in München ?",
        "Wie komme ich zum Büro in München?",
        "Welche Notfallkontakte gibt es in München?",
        "Wo bekomme ich meinen Mitarbeiterausweis in München?",
        "Wo befindet sich das IT Walk-In Center in München?",
        "Was gibt es in der Kantine in Hannover?",
        "Wie komme ich zum Büro in Hannover?",
        "Welche Notfallkontakte gibt es in Hannover?",
        "Wo bekomme ich meinen Mitarbeiterausweis in Hannover?",
        "Wo befindet sich das IT Walk-In Center in Hannover?",
        "Mit welcher App kann ich meine Geschäftsreisen und Spesenabrechnungen einfach verwalten und einreichen?",
        "Wo kann ich bequem auf personalbezogene Informationen und Aufgaben an einem Ort zugreifen und diese verwalten.",
        "Von wo aus ich auf personalbezogene Informationen und Aufgaben zugreifen und diese verwalten kann.",
        "Welche App ist für die Verwaltung und Verfolgung von ServiceNow-Vorfällen gedacht, die den normalen Servicebetrieb stören?",
        "Wie bucht/verwaltet man einen Besprechungsraum am Arbeitsplatz.",
        "Wo erhalte ich Angaben zu meinem Vermögen?",
        "Wie erhalte ich Details zu meinen Vermögenswerten?",
        "Wo kann ich den Status meiner IT-Bestellung bei E.ON einsehen/überprüfen?",
        "Waar kan ik relevante gegevens over goederen en diensten krijgen?\nWaar kan ik informatie krijgen over goederen en diensten?",
        "Aanvraag voor goederendienst relevante functies?",
        "Wie erhalte ich relevante Details zu Waren und Dienstleistungen?",
        "Wie erhalte ich den Status von Waren und Dienstleistungen?",
        "Wo kann ich sehen, dass die Waren und Dienstleistungen aktualisiert wurden?",
        "Wie überwache und analysiere ich meinen (unseren) Energieverbrauch und optimiere ihn?",
        "Wo können wir unseren Energieverbrauch überwachen und analysieren und an einem Ort optimieren",
        "Wie kann ich die Rechnungen einfach (effizient) genehmigen\n(indem ich alle relevanten Informationen habe)",
        "Wie genehmige ich die Rechnungen?",
        "Was soll die App den Nutzern bei der Vorbereitung auf Vorstandssitzungen helfen.",
        "Was soll die App für Vorstandssitzungen unterstützen?",
        "Wat is een digitale certificaat-app?",
        "Digitale certificaat-app?",
        "Welches ist das Werkzeug für die Verwaltung von Verteilerlisten (DL), die in der E-Mail-Kommunikation innerhalb der Organisation verwendet werden?",
        "Welches ist das Werkzeug für die Verwaltung von Verteilerlisten (DL), die für die E-Mail-Kommunikation verwendet werden?",
        "Wat is een digitaal leerplatform voor medewerkers van E.ON?",
        "Wat is het digitale leerplatform voor medewerkers van E.ON?",
        "Wie heißt die App, mit der Ideen und Vorschläge eingereicht und bewertet werden können?",
        "Wat een krachtig visualisatiehulpmiddel is met geavanceerde planningsmogelijkheden.",
        "Wat is de visualisatietool met geavanceerde planningsmogelijkheden.",
        "Was sind Eigenentwicklungen auf Basis der Business Technology Plattform (BTP) von SAP?",
        "Welche App wurde entwickelt, um das Management der Funktionstrennung (Segregation of Duties) zu optimieren und zu digitalisieren?",
        "Welches Tool ist entscheidend für die Aufrechterhaltung eines robusten internen Kontrollsystems und den Schutz Ihrer Geschäftsabläufe?",
        "Welche App hilft Ihnen dabei, alle relevanten Gefährdungsbeurteilungen schnell und einfach im Blick zu behalten?",
        "Welche App wird für die Verwaltung und Kommunikation der langfristigen Anreizprogramme von E.ON verwendet?",
        "Wer nutzt die beqom-App?",
        "Welche App ermöglicht es, aktuelle Stellenangebote mit talentierten Personen in Ihrem Netzwerk zu teilen?",
        "Wie können Benutzer analytische Anwendungen und Workflows verwalten und teilen?",
        "Welche App bietet Echtzeit-Updates zu Umwelt-, Gesundheits- und Sicherheitsvorschriften (EHS)?",
        "Wie kann man einen sicheren und regelkonformen Arbeitsplatz aufrechterhalten, Risiken reduzieren und die betriebliche Effizienz verbessern?",
        "-Wie kann ich in Echtzeit Live-Umfragen, Q&A-Sitzungen und Quizze durchführen und so ein dynamisches und interaktives Erlebnis für das Publikum schaffen?",
        "-Welche ist die zentrale interne Anwendungsplattform?",
        "-Welche App kann verwendet werden, um Dienstleistungen für eine Video-/TV-Produktion am Brüsseler Platz zu buchen?",
        "Wie kann ich die Prozesse im Zusammenhang mit dem Bankkontenmanagement elektronisch optimieren und verwalten?",
        "Welche App übernimmt Bürgschaften und Garantien für Geschäftseinheiten (BUs) des Konzerns gegenüber externen Kreditgebern?",
        "Wie kann ich die Dokumentenverwaltungsprozesse innerhalb der Organisation optimieren?",
        "Welche App bietet eine umfassende Lösung für das Dokumentenmanagement?",
        "Welche App bietet Echtzeiteinblicke in Liquidität und Bargeldbestände, um fundiertere Entscheidungen im Kapital- und Risikomanagement zu ermöglichen?",
        "Welche App optimiert Arbeitsabläufe und verbessert die finanzielle Leistung?",
        "Welche App kann für die Bearbeitung von Kreditanträgen und das Management von Kreditrisiken verwendet werden?",
        "Welche ist das zentrale Wissensrepository von E.ON für Kunden- und Marktanalysen?",
        "Welche App wird von Mitarbeitenden und Führungskräften im Vereinigten Königreich verwendet, um Leistungen, Ziele und Beurteilungen zu dokumentieren?",
        "Welche App kann für Schulungen und Bewertungen im Bereich Bildschirmarbeitssicherheit (Health and Safety) verwendet werden?",
        "Welche App wird verwendet, um den Einstufungsprozess für Führungskräfte zu starten?",
        "Mit welchem Tool können Sie Geschäftspartner überprüfen?",
        "Wie kann ich verpflichtende Sicherheitsschulungen durchführen?",
        "Wie kann ich Daten im Zusammenhang mit Qualitätssicherung oder Normdokumenten verwalten, bereitstellen und aktualisieren?",
        "Welche App wird für Budgetierung und Planung, Konsolidierung, Risikomanagement und Managementberichterstattung verwendet?",
        "Welche App ist eine Anwendung für Corporate Performance Management?",
        "Welche App ist eine Anwendung für das Enterprise Risk Management (ERM)?",
        "Welche App dient der Erstellung von Dashboards für Group Financial, ESG-Berichterstattung, Unit Financial und FSOTC-Dashboards?",
        "Welche App ist eine Online-Bibliothek mit Buchzusammenfassungen, Artikeln und weiteren Lernformaten, die alle geschäftsrelevanten Kompetenzen abdecken?",
        "Welche App kann für Soft Skills und fachliche Kompetenzen herangezogen werden?",
        "Wer ist Leonhard Birnbaum?",
        "Wer ist Leo?",
        "Wer ist der Vorstandsvorsitzende von E.ON?\n\nWer ist der CEO von E.ON?",
        "Können Sie mir den Link zu EON GPT mitteilen?\n\nKannst du mir den Link zu EON GPT mitteilen?",
        "Was sind die Anwendungsfälle der Corporate Apps?",
        "Was sind die Anwendungsfälle für die Suchfunktion in Workplace Apps?",
        "Praveen kumar\nPraveen",
        "How to go about blocked website?",
        "Why can't I access some Google websites?",
        "I can not install Google Chrome add-ins",
        "How can I order a Cloud PC",
        "How do I sign-in",
        "How to take notes in a scheduled meeting?",
        "Signature is not displayed correctly",
        "How to leave a Plan?",
        "What if the Tunnel app keeps disconnecting?",
        "Why can’t I see the “Profile Downloaded” option in my settings?",
        "How can I fix slow Wi-Fi speeds?",
        "Can I restrict access for people to only have access to individual Channels within my Team?",
        "I have Calendar synchronization issues",
        "Appointments cannot be accepted",
        "How can I add public mailbox",
        "The encrypted emails are not readable.",
        "I am receiving Bounce message (Non delivery report)",
        "I have not received any emails since last 3 days",
        "Not able to hear call ring",
        "Keyboard automatically types",
        "Where can I find the contact information for the relevant safety officer at EON?",
        "I want to find my monthly payslip on the HR portal",
        "Where can employees find information on public transport discounts and offers, such as the BahnCard, Jobticket, and company-specific tickets in Essen, provided by EON?",
        "Where is the fitness room located and are there other sports classes available on campus?",
        "Where can I find information about the leasing bike model?",
        "Where can I find more information about the Modern Workplace at E.ON?",
        "Where can I find detailed information about travel security provided by E.ON?",
        "Where can I find my KID and personal number on the HR portal?",
        "Where can I find information about E.ON's art, culture, and design projects online?",
        "Where can I find the current stock price of E.ON?",
        "Where can I find the specific Corona regulations for E.ON locations such as Essen and Hannover?",
        "Where can I request a height-adjustable desk?",
        "Can I pre-order my food at E.ON canteens?",
        "Where can I find detailed information about my IT assets?",
        "How can I enroll for Github Training",
        "Github Training",
        "How to do Github Training",
        "Show me Google Sheets trainings",
        "How to learn Google Sheets",
        "Google Sheets",
        "How can I enroll for Data lakes and Lakehouses with Spark and Azure Databricks training Training",
        "How can I enroll for Spark and Data Lakes Training",
        "How can I enroll for Azure Spark Databricks Essential Training",
        "How can I enroll for Swift 5 esencial training",
        "How can I enroll for Podstawy doskonalosci operacyjnej training",
        "How to Help Employees with Disabilities Thrive",
        "How can we support employees with disabilities",
        "How can we support workers with disabilities",
        "As a manager, how can we help employees with Disabilities",
        "How can we bring equality among workers with disabilities",
        "Is there any trainings for employees with disability to read and write",
        "Trainings on migration from classic to modern sites",
        "Qualities of Leadership",
        "Leadership qualities",
        "Skills of Leadership",
        "What are the qualities of positive leadership",
        "How to be a positive Leader",
        "Importance of Cyber Security",
        "Why is Cyber Security important"
    ],
    "Office 365": [
        "I want to add a shared mailbox to outlook",
        "wie kann ich meine token in outlook aktivieren?",
        "Um eine geteilte Inbox zu entfernen, folgen Sie diesen Schritten:\n\n1. Ã–ffnen Sie Outlook.\n2. Gehen Sie zur linken Seitenleiste, suchen Sie die geteilte Inbox, die Sie entfernen mÃ¶chten.\n3. Klicken Sie mit der rechten Maustaste auf die geteilte Inbox.\n4. WÃ¤hlen Sie die Option â€žOrdner entfernenâ€œ oder â€žEntfernenâ€œ aus dem KontextmenÃ¼.\n\nFalls Sie weitere UnterstÃ¼tzung benÃ¶tigen oder Probleme auftreten, kÃ¶nnen Sie sich gerne an die IT-Abteilung Ihres Unternehmens wenden oder in den internen Ressourcen nachsehen. <br /><b>Source: E.ON Knowledge Base, E.ON MyGenius</b>",
        "Wie kann ich ein gemeinsames Postfach in MS Outlook hinzufÃ¼gen?",
        "How can I use Power Automate to streamline workflows and share applications within my organization using O365?",
        "Wo speichere ich meine Daten? Speicherung von Daten? OneDrive-Speicher?",
        "Wo kann ich Anleitungen und Benutzerhandbücher zu O365 finden?",
        "What to do with Error 404 in SharePoint",
        "How to migrate SharePoint data",
        "Why I'm not able to see attachments in Outlook",
        "I’m getting errors when trying to encrypt emails in Outlook online.",
        "Outlook online is freezing up.",
        "My Outlook shows “disconnected “ error",
        "Is there any trainings on SharePoint",
        "How can i learn SharePoint online",
        "SharePoint Quick Tips",
        "Development on SharePoint sites"
    ],
    "Compliance": [
        "What are the steps and contact links for reporting different types of incidents, such as safety, security, compliance, and cyber security?",
        "Where can I access the compliance and integrity guidelines published by E.ON?",
        "Where can I find the details of my Compliance contact person?",
        "Where can I find detailed information about compliance and its key topics at E.ON?",
        "Where can I find information about the Chief Compliance Officer at E.ON?",
        "Where can I find information about the contact person for insider law compliance?",
        "Where can I find a list of Antitrust Experts for consultation?",
        "Vorfallbericht\nWie meldet man einen Vorfall?\nEinen Vorfallbericht öffnen?\nWie sollte ein Ereignis gemeldet werden?\nWie kann ich einen Vorfall melden?\nFrage des Bots: Welcher Vorfall? Cyber-Vorfall, Compliance usw. Arbeitsunfall Sagety Prisma, Sicherheitsmodul in Prisma, …",
        "Wo kann ich die aktuellen Compliance-Regeln finden?",
        "Wo finde ich den Verhaltenskodex? Wo finde ich die Mitarbeiterrichtlinien?",
        "Wer ist meine Kontaktperson in der Compliance?",
        "Wie kann ich anonym Hinweise geben? E.ON Whistleblower-System E.ON Whistleblower-Hotline Richtlinien zum Umgang mit Compliance-Berichten - Insbesondere im E.ON Whistleblowing-System",
        "Wer ist der Chief Compliance Officer bei E.ON?",
        "Wer ist mein Ansprechpartner bezüglich Insiderrecht?",
        "Wer ist mein Ansprechpartner für Antitrustrecht?",
        "Was muss ich über Geldwäsche wissen?",
        "Von wo aus wir/ich die notwendigen Richtlinien für Marketing- und Kommunikationsaktivitäten bei E.ON einsehen können",
        "Welche App wird verwendet, um Richtlinien in den Bereichen IFRS, Controlling, HGB und ESG bereitzustellen?",
        "Welche App stellt die Richtlinien ihres Unternehmens bereit?",
        ],
    "About MyHelp": [
        "What are the product features in MyHelp platform?",
        "What are Self Service features in MyHelp?",
        "Who is responsible for corp requirements of Myhelp?",
        "Who is the Product Owner of Myhelp?",
        "Who is the Business Product Owner of Myhelp?",
        "Who is the UI &UX Architect of Myhelp?",
        "Who will be responsible for Communication related to MyHelp?",
        "Who is the Technical Product Owner (TPO) of Myhelp?",
        "What can MyHelp do?",
        "How should I talk to MyHelp?",
        "Which workflows (apps) are available on MyHelp?",
        "What types of information can MyHelp help me find?",
        "Which resources can MyHelp search for?",
        "How can I improve the quality of MyHelp answers?",
        "Will my conversations in MyHelp be visible to other users?",
        "What are the Tips and tricks of MyHelp?",
        "What's New in MyHelp?",
        "Was sind die Produktfunktionen der MyHelp-Plattform?",
        "Was sind die Self-Service-Funktionen in MyHelp?",
        "Wer ist für die unternehmensweiten Anforderungen verantwortlich Myhelp?",
        "Wer ist der Product Owner Myhelp?",
        "Wer ist der Business Product Owner Myhelp?",
        "Wer ist der UI- & UX-Architekt Myhelp?",
        "Wer ist für die Kommunikation rund um MyHelp verantwortlich Myhelp?",
        "Product Owner Myhelp\nTechnical product owner MyHelp\nPraveen Kumar",
        "Was kann MyHelp tun?",
        "Wie soll ich mit MyHelp sprechen?",
        "Welche Workflows (Apps) sind auf MyHelp verfügbar?",
        "Welche Arten von Informationen kann MyHelp finden?",
        "Welche Quellen durchsucht MyHelp?",
        "Wie kann ich die Qualität der MyHelp-Antworten verbessern?",
        "Werden meine Unterhaltungen in MyHelp für andere Benutzer sichtbar sein?",
        "Was sind die Tipps und Tricks für MyHelp?"
    ]
}